added testID prop
Eliav2/react-native-collapsible-view pull request #8
Opened 2021-07-08 13:59 UTC by lucas1feliciano0

2021-07-08 14:01 UTC, gilberthmob approved these changes

2021-07-08 16:26 UTC, Eliav2 requested changes

2021-07-08 16:26 UTC, Eliav2 commented on index.js
> +  testID = "",
testID is not a good name.
rename to `touchableWrapperProps` .
also add `touchableWrapperStyle` properly.

2021-07-08 16:26 UTC, Eliav2 commented on index.js
>        style={[styles.container, style]}
concat `touchableWrapperStyle` here.

2021-07-08 16:26 UTC, Eliav2 commented on index.js
> +  TouchableOpacity,
make it editable.
 `TouchableOpacity` can be choosed to other using a new `TouchableComponent` prop.

2021-07-08 16:28 UTC, Eliav2 commented on index.js
>    activeOpacityFeedback = 0.3,
add `TouchableComponent=TouchableOpacity ` here

2021-07-08 21:26 UTC, Eliav2 commented
Very well fellow, will soon be  next to a computer and will confirm and merge.. 👍👌🏻👌🏻

2021-07-12 11:07 UTC, Eliav2 approved these changes

2021-07-12 11:13 UTC, Eliav2 commented
hey friend, great pull request:
one last thing so could fully accept your pull:
change the readme and add `touchableWrapperStyle`, `touchableWrapperProps`, and `TouchableComponent` props and add a proper description.

also, if you want, change the version in the package.json file from v1.3.0 to v1.4.0. also. don't forget to update the Vectsions section in the Readme.md.
make sure to test the package before submitting the changes.

then, I will merge the request and will publish v1.4.0. you will appear as a contributor on this repo.

2021-07-21 20:17 UTC, merged

2021-07-21 20:35 UTC, Eliav2 commented
published v1.4.0